AWSTemplateFormatVersion: '2010-09-09'
Description: AWS CloudFormation template for Pokedex Gui React application hosted on S3 and CloudFront.

Parameters:
  BucketName:
    Type: String
    Description: Name for the S3 bucket where the React app will be hosted. Must be globally unique.
    Default: pokedex-gui-frontend-bucket-seunomeunico-2025-05-30-2150 # <<<<<<<<<<<<<<<< IMPORTANTE: Mude para um nome MUITO ÚNICO

Resources:
  # Recurso para criar o CloudFront Origin Access Identity (OAI)
  CloudFrontOAI:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: OAI for Pokedex Gui S3 Bucket

  # S3 Bucket para hospedar o frontend React
  FrontendS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      AccessControl: Private # OAI fará o acesso
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html # Para SPAs como React, todas as rotas caem em index.html

  # Políticas para o S3 Bucket para permitir acesso do CloudFront via OAI
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref FrontendS3Bucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              # Referência dinâmica ao ARN do OAI recém-criado
              AWS: !Sub 'arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ${CloudFrontOAI}'
            Action: s3:GetObject
            Resource: !Sub 'arn:aws:s3:::${FrontendS3Bucket}/*'

  # Distribuição CloudFront para servir o conteúdo do S3
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          - Id: FrontendS3Origin
            DomainName: !GetAtt FrontendS3Bucket.RegionalDomainName
            S3OriginConfig:
              # Referência dinâmica ao OAI recém-criado
              OriginAccessIdentity: !Sub 'origin-access-identity/cloudfront/${CloudFrontOAI}'
        Enabled: 'true'
        DefaultRootObject: index.html
        CustomErrorResponses:
          - ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /index.html
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
          CachedMethods:
            - GET
            - HEAD
          TargetOriginId: FrontendS3Origin
          ViewerProtocolPolicy: redirect-to-https
          Compress: true
          ForwardedValues:
            QueryString: 'false'
            Cookies:
              Forward: none
        ViewerCert:
          CloudFrontDefaultCertificate: 'true'

Outputs:
  S3BucketName:
    Description: Name of the S3 bucket hosting the React app.
    Value: !Ref FrontendS3Bucket
    Export:
      Name: !Sub '${AWS::StackName}-S3BucketName'
  CloudFrontDomainName:
    Description: Domain name of the CloudFront distribution.
    Value: !GetAtt CloudFrontDistribution.DomainName
    Export:
      Name: !Sub '${AWS::StackName}-CloudFrontDomainName'