# .github/workflows/ci-cd.yml

name: Pokédex Gui - CI/CD Completo

on:
  push:
    branches:
      - main # Dispara o workflow a cada push na branch main
  workflow_dispatch: {} # Permite execução manual

permissions:
  contents: read # Permite ler o código do repositório

jobs:
  # Job 1: Integração Contínua (Build e Teste)
  build_and_test: # <<<<<<<<<<<<<<<< Nome da job de CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test

      - name: Build React App
        run: npm run build
        env:
          CI: false # Desabilita o erro de "warnings as errors"

      # A etapa de Upload Build Artifact não é mais necessária aqui
      # pois a job de deploy vai refazer o build.
      # - name: Upload Build Artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: react-app-build
      #     path: build/

  # Job 2: Implantação Contínua (Deploy)
  deploy: # <<<<<<<<<<<<<<<< Nome da job de CD
    runs-on: ubuntu-latest
    environment: production
    needs: build_and_test # <<<<<<<<<<<<<<<< Esta job SÓ roda se 'build_and_test' for bem-sucedida

    steps:
      - name: Checkout code
        uses: actions/checkout@v2 # Checkout novamente para ter o código no runner de deploy

      - name: Install dependencies
        run: npm install # <<<<<<<<<<<<<<<< Reinstala as dependências
      
      - name: Build React App
        run: npm run build # <<<<<<<<<<<<<<<< Refaz o build da aplicação
        env:
          CI: false

      # A etapa de Download Build Artifact não é mais necessária aqui,
      # pois o build está sendo feito novamente nesta job.
      # - name: Download Build Artifact
      #   uses: actions/download-artifact@v4
      #   with:
      #     name: react-app-build

      - name: Configure AWS Credentials for Academy
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Deploy CloudFormation Stack (Frontend S3)
        run: |
          aws cloudformation deploy \
            --template-file cloudformation-frontend.yml \
            --stack-name PokedexGuiFrontendStack \
            --capabilities CAPABILITY_IAM \
            --parameter-overrides BucketName=pokedex-gui-frontend-bucket-2025-05-30-2150

      - name: Sync S3 Bucket
        run: |
          # O caminho agora é diretamente 'build/' pois o build foi refeito nesta job
          aws s3 sync ./build/ s3://$(aws cloudformation describe-stacks --stack-name PokedexGuiFrontendStack --query 'Stacks[0].Outputs[?OutputKey==`S3BucketName`].OutputValue' --output text) \
          --delete # --delete remove arquivos que não existem mais no build