# .github/workflows/sonarcloud.yml

name: SonarCloud analysis

on:
  push:
    branches: [ "containers-ecs" ] # Dispara na branch correta
  pull_request:
    branches: [ "containers-ecs" ] # Dispara para Pull Requests na branch correta
  workflow_dispatch: {} # Permite execução manual

permissions:
  contents: read # Permite ler o código do repositório
  pull-requests: read # Permite que o SonarCloud decore PRs com resultados de análise
  id-token: write # Necessário para autenticação com SonarCloud via OpenID Connect (melhor prática)

jobs:
  Analysis:
    runs-on: ubuntu-latest # Executa em um ambiente Ubuntu

    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # Usar a versão mais recente para melhor segurança e compatibilidade
        with:
          fetch-depth: 0 # Necessário para a análise completa do SonarQube (histórico de commits)

      - name: Set up Node.js
        uses: actions/setup-node@v3 # Configura o ambiente Node.js, se o projeto for JavaScript/TypeScript
        with:
          node-version: '18' # Ajuste para a versão do Node.js do seu projeto React

      - name: Run SonarCloud Analysis
        uses: SonarSource/sonarcloud-github-action@v2.2 # Recomendo usar a tag de versão (v2.2) em vez do hash específico para atualizações automáticas de patches
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} # Seu token pessoal do SonarCloud (deve estar nos secrets do GitHub)
        with:
          args: > # Múltiplas linhas para argumentos do scanner
            -Dsonar.projectKey=HaylenoHossoe_pokedex-gui # <--- CORRIGIDO AQUI: SEU PROJECT KEY
            # -Dsonar.organization=sua-organizacao # Descomente e preencha se você tiver uma organização no SonarCloud
            # -Dsonar.sources=. # Opcional, o padrão é o diretório base do projeto
            # -Dsonar.tests=src # Opcional, se tiver diretório específico para testes
            # -Dsonar.test.inclusions=**/*.test.js,**/*.test.jsx # Exemplo para testes React
          projectBaseDir: . # O diretório base do seu projeto, padrão é o diretório raiz do repositório